# Generated by Django 3.2 on 2023-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_pricing_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default_img_for_not_pro_user/default_img_for_not_pro_user.jpg', upload_to='thumbnails/'),
        ),
    ]
