# Generated by Django 4.2 on 2023-06-11 19:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_video_aliexpress_order_video_aliexpress_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='read_more_text_that_comes_with_ads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
