# Generated by Django 4.2 on 2023-06-15 20:51

import content.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='name_of_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_name', to='content.store'),
        ),
    ]
